In [ ]:
import numpy as np

# Создание массива из обычного списка Python
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Массив из списка:", array_from_list)

# Создание двумерного массива из вложенного списка
matrix_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix_data)
print("Двумерный массив:")
print(matrix)

# Создание массива, заполненного нулями
zeros_array = np.zeros(5)
print("Массив из нулей:", zeros_array)

# Создание массива, заполненного единицами
ones_array = np.ones((3, 3))  # 3x3 матрица из единиц
print("Матрица 3x3 из единиц:")
print(ones_array)

# Создание массива с последовательностью чисел
range_array = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("Массив от 0 до 10 с шагом 2:", range_array)
print("\nАтрибуты матрицы:")
print("Форма (shape):", matrix.shape)    # Размерность массива
print("Тип данных (dtype):", matrix.dtype)  # Тип элементов массива
print("Количество элементов:", matrix.size)  # Общее количество элементов


# Получение отдельного элемента (индексация начинается с 0)
print("\nИндексирование:")
print("Элемент [0,0]:", matrix[0, 0])  # Первый элемент первой строки
print("Элемент [2,1]:", matrix[2, 1])  # Второй элемент третьей строки

# Извлечение подмассива с помощью срезов
print("\nСрезы:")
print("Первая строка:", matrix[0, :])     # Вся первая строка
print("Второй столбец:", matrix[:, 1])    # Весь второй столбец
print("Подматрица 2x2:")
print(matrix[0:2, 0:2])  # Первые две строки и первые два столбца

# Создаем два массива для операций
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("\nВекторные операции:")
print("Массив a:", a)
print("Массив b:", b)

# Поэлементное сложение массивов
sum_arrays = a + b
print("a + b:", sum_arrays)

# Поэлементное умножение массивов
mult_arrays = a * b
print("a * b:", mult_arrays)

# Базовые статистические операции
print("\nБазовые статистики для массива a:")
print("Среднее значение:", np.mean(a))
print("Сумма всех элементов:", np.sum(a))
print("Минимальное значение:", np.min(a))
print("Максимальное значение:", np.max(a))
print("Стандартное отклонение:", np.std(a))

# Статистика для матрицы
print("\nСтатистика для матрицы:")
print("Среднее по всем элементам:", np.mean(matrix))
print("Сумма по столбцам:", np.sum(matrix, axis=0))  # axis=0
print("Среднее по строкам:", np.mean(matrix, axis=1))  # axis=1

Массив из списка: [1 2 3 4 5]
Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Массив из нулей: [0. 0. 0. 0. 0.]
Матрица 3x3 из единиц:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Массив от 0 до 10 с шагом 2: [0 2 4 6 8]

Атрибуты матрицы:
Форма (shape): (3, 3)
Тип данных (dtype): int64
Количество элементов: 9

Индексирование:
Элемент [0,0]: 1
Элемент [2,1]: 8

Срезы:
Первая строка: [1 2 3]
Второй столбец: [2 5 8]
Подматрица 2x2:
[[1 2]
 [4 5]]

Векторные операции:
Массив a: [1 2 3 4]
Массив b: [5 6 7 8]
a + b: [ 6  8 10 12]
a * b: [ 5 12 21 32]

Базовые статистики для массива a:
Среднее значение: 2.5
Сумма всех элементов: 10
Минимальное значение: 1
Максимальное значение: 4
Стандартное отклонение: 1.118033988749895

Статистика для матрицы:
Среднее по всем элементам: 5.0
Сумма по столбцам: [12 15 18]
Среднее по строкам: [2. 5. 8.]


In [5]:
#!connect jupyter --kernel-name python3 --kernel-spec python3

In [6]:
#!connect jupyter --kernel-name python3 --kernel-spec python3